### ISSUE TITLE
iVentoy using Chrome instead of default browser

### ISSUE THREAD

**Issue by asheroto** [ventoy/PXE#15]
I'm using Brave Browser as my default, but have Chrome installed.

When iVentoy launches, it opens Chrome instead of my default browser.

Windows 11, iVentoy 64-bit.

Thank you 😊

**Comment by AnomSanjaya** [comment]
Did You Know: In first release of VentoyPlugson, they use Firefox as default browser whatever your default browser was selected, then they change to Chrome since Ventov 1.0.80+ instead of Firefox

But, if u want other browser to chain iVentoy for this time, u must uninstall Chrome and change to ur favorite browser default, and iVentoy will open ur favorite browser as expected

*My Windows 10, only have Firefox (my default) browser installed (Egde totally disabled), so iVentoy will open Firefox and running properly

**Comment by asheroto** [comment]
Hmm..

Ideally all that needs to happen is the opening of an http protocol URL with shell.

Example, shell run https://google.com and it will open the default browser. 😊

**Comment by AnomSanjaya** [comment]
> Example, shell run https://google.com and it will open the default browser. 😊

I dont know if this command will work in WIndows, since default browser based from associate extension (.htm or .html) and iVentoy doesnt care about it

**Comment by ventoy** [comment]
You can run `iVentoy_64.exe /F`  then it will open the default browser.

**Comment by asheroto** [comment]
> I dont know if this command will work in WIndows, since default browser based from associate extension (.htm or .html) and iVentoy doesnt care about it

I have `.html` and `.htm` files opening with Brave but iVentoy still opens Chrome.

> You can run `iVentoy_64.exe /F` then it will open the default browser.

Yes, that works, but why not make the default browser the default browser for iVentoy? 😊

**Comment by ventoy** [comment]
I only test the web ui in google chrome so I made it the default.

**Comment by asheroto** [comment]
If someone doesn't use Chrome, then it won't work?

**Comment by ventoy** [comment]
NO.
It just test that whether Chrome was installed, if so then use it, if not then use default browser.

**Comment by asheroto** [comment]
Ah, okay. Well that's good. I guess I don't understand why not just use the default browser? Haha.

**Comment by ventoy** [comment]
For example on some old Windows system people may have installed chrome, but the default browser may still be very old IE.

**Comment by asheroto** [comment]
Ah I see. Okay. I will go ahead and close this Issue.
